### ISSUE TITLE
10Pro，写入nfc出错

### ISSUE THREAD

**Issue by xzl0326** [XFY9326/MiLinkNFC#1]
![Screenshot_2024-02-20-21-13-29-306_tool xfy9326 milink nfc](https://github.com/XFY9326/MiLinkNFC/assets/52959229/31ff02dc-37a1-48ae-b649-e7beadc79963)

**Comment by Jankinsu** [comment]
刷的哪个版本的系统？

**Comment by xzl0326** [comment]
> 刷的哪个版本的系统？

1.0.24.1.29DEV
我在QQ群里也发了

**Comment by XFY9326** [comment]
该问题可能与当前使用的设备有关，无法复现
