### ISSUE TITLE
写入标签贴时提示未知错误？

### ISSUE THREAD

**Issue by youlan2333** [XFY9326/MiLinkNFC#2]
![Screenshot_2024-03-06-20-09-19-166_tool.xfy9326.milink.nfc.jpg](https://github.com/XFY9326/MiLinkNFC/assets/64688148/34e6443f-d49c-4b69-b1e3-2a15cfdadcbb)

**Comment by XFY9326** [comment]
目前正在着手尝试修复这个问题

**Comment by XFY9326** [comment]
目前我无法复现也未找到修复方案，1.8.4和1.9版本都尝试去修复了，依然无法使用的话建议更换手机写入NFC标签。

**Comment by XFY9326** [comment]
最新版最终修复了这个问题
