### ISSUE TITLE
如果能一碰就可以网络协同就好了

### ISSUE THREAD

**Issue by earthxwx** [XFY9326/MiLinkNFC#3]
* 方便的就是网络功能了, 如果能一碰即用就好了, 省去了操作和刚靠近电脑的搜索时间
* 如果还能合并链接热点和互联共享两个功能就好了, 省去了两个操作

**Comment by XFY9326** [comment]
这个应用只是提供了一个方便的工具用来模拟写入小米一碰妙享NFC数据，并不能提供更多的相关功能。所以如果小米一碰妙享能够实现这样的一碰网络连接功能了，我就可以通过分析NFC数据帮助大家做到这一点。就目前来看并没有这样提供的功能。
