### ISSUE TITLE
一碰妙享->测试屏幕镜像功能闪退

### ISSUE THREAD

**Issue by shinemymoon** [XFY9326/MiLinkNFC#4]
设备类型：电脑
触发方式：虚拟NFC标签
蓝牙MAC地址：通过“扫描蓝牙设备的MAC地址”找到电脑MAC，复制后粘贴

点击投屏，应用闪退

[bugreport-garnet-UKQ1.231003.002-2024-03-22-10-25-01.zip](https://github.com/XFY9326/MiLinkNFC/files/14716419/bugreport-garnet-UKQ1.231003.002-2024-03-22-10-25-01.zip)

**Comment by XFY9326** [comment]
根据错误日志中的内容，我目前认为这个问题是你当前的系统中不存在可以接收NFC触碰信息的应用导致的。这个一般是不会发生的，但我会为此增加错误提示而不是放任其崩溃。所以修复后“虚拟NFC标签”功能可能会弹出错误提示且依然无法使用，这并不是这个App的问题。

**Comment by XFY9326** [comment]
闪退问题已在 1.9.4 修复

**Comment by shinemymoon** [comment]
新版本确实会弹出错误提示了，关于“当前的系统中不存在可以接收NFC触碰消息的应用”，我有疑问如下：
1. 妙享不是HyperOS自带的系统级功能吗，难道还要额外安装APP？
2. 如果不需要额外安装APP，是否需要设置接收消息的应用，如何设置？

**Comment by XFY9326** [comment]
确实是系统功能，但是理论上来说不应该出现找不到可以处理NFC消息的问题，我在自己的设备上测试了不存在这个问题。如果“虚拟NFC”方式不能使用你可以试试用“互联通信服务”的触发方式，如果依然无法使用那可能系统设置中限制了当前App不能跳转打开其它App之类的。你可以在一碰妙享界面点击右上角的问号，查看自己系统中的一些软件是否都功能齐全。
