### ISSUE TITLE
Not compatible with AS 2023

### ISSUE THREAD

**Issue by shinemymoon** [XFY9326/MiLinkNFC#5]
Build Error:
The project is using an incompatible version (AGP 8.3.1) of the Android Gradle plugin. Latest supported version is AGP 8.2.2

About:
Android Studio Hedgehog | 2023.1.1 Patch 2
Build #AI-231.9392.1.2311.11330709, built on January 19, 2024
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-101-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (231.9225.5)
    com.xiaomi.plugin.as.assistant (1.2.11)

Current Desktop: ubuntu:GNOME

**Comment by XFY9326** [comment]
Try updating your Android Studio to the latest version (Iguana 2023.2.1 Patch1) to fix this problem.

**Comment by shinemymoon** [comment]
2023.2.1 is Great
